# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ayush7380
service: aws-say-hello
frameworkVersion : "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

functions:
  ayushVscodefn:
    handler: hello.ayush
    events:
      - httpApi:
          path: /hello
          method: get
  ayushVsCodeWelcome:
    handler: welcome.welcome
    events: 
      - httpApi:
          path: /welcome
          method: get
